const mongoose=require('mongoose')
const tradeRequestSchema=new mongoose.Schema({
    id:{
        type:String,
        required:true
    },
   itemProvided:{
    src:{
        type:String,
        required:true
    },
    title:{
        type:String,
        required:true
    },
    text:{
        type:String
    },
    looksFor:{
        type:String
    },
    free:{
        type:Boolean,
        required:true
    },
    id:{
        type:String,
        required:true
    },
    userId:{
        type:Number,
        required:true
    }
   },
   itemWanted:{
    src:{
        type:String,
        required:true
    },
    title:{
        type:String,
        required:true
    },
    text:{
        type:String
    },
    looksFor:{
        type:String
    },
    free:{
        type:Boolean,
        required:true
    },
    id:{
        type:String,
        required:true
    },
    userId:{
        type:Number,
        required:true
    }
   },
   completed:{
       type:Boolean,
       default:false
   }
})
const TradeRequest=mongoose.model('TradeRequest',tradeRequestSchema);
module.exports=TradeRequest;
